name: Go CI for api_mocks


on:
  pull_request:
    paths:
      - 'api_mocks/**'

jobs:
  build:

    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: cd api_mocks && go build -v ./...

      - name: Test
        run: cd api_mocks && go test -v ./...
